title: Hello Title
author: Me
email: doesit@matter.com
description: > # this means to ignore newlines until "baseurl:"
  Greetings from 3rd world from the sun.

# social links
twitter_username: shintatt
github_username:  st-wong
show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-merlot
